name: Docker Image CI/CD

on:
  push:
    branches: ["mithril-socket"]
  pull_request:
    branches: ["mithril-socket"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/redcloud442/mithril:prod-be-socket-${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: "v1.25.4"

      # - name: Create kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # - name: Deploy to Kubernetes
      #   run: |
      #     echo "🚀 Updating image in deployment 'mithril-socket-be'... .."
      #     kubectl set image deployment/mithril-socket-be mithril-socket-be=ghcr.io/redcloud442/mithril:prod-be-socket-${{ env.SHORT_SHA }} -n mithril-socket

      #     echo "⏳ Waiting for rollout to complete..."
      #     kubectl rollout status deployment/mithril-socket-be -n mithril-socket
